version: '3.5'

services:
  # Creates self signed tls certificates. Remove if you
  # use your own.
  ssl:
    image: jeboehm/mailserver-ssl:latest
    build: ./ssl
    container_name: mailserver_ssl
    env_file: .env
    volumes:
      - data_tls:/media/tls:rw

  # Responsible for storing users and their aliases. Remove
  # if you already have a MySQL server.
  db:
    image: jeboehm/mailserver-db:latest
    build: ./db
    container_name: mailserver_db
    restart: on-failure:5
    env_file: .env
    volumes:
      - data_db:/var/lib/mysql

  # The Mail Transfer Agent (Postfix) receives incoming mail
  # on TCP port 25.
  mta:
    image: jeboehm/mailserver-mta:latest
    build: ./mta
    container_name: mailserver_mta
    restart: on-failure:5
    env_file: .env
    volumes:
      - data_tls:/media/tls:ro
      # For using external certificates uncomment the following lines
      # and change the path on the left side of the colon.
      # - /home/user/certs/mail.example.com.crt:/media/tls/mailserver.crt:ro
      # - /home/user/certs/mail.example.com.key:/media/tls/mailserver.key:ro

  # The Mail Delivery Agent (Dovecot) is responsible for storing
  # incoming mail into a users mailbox and also delivers them
  # via POP3 or IMAP4.
  mda:
    image: jeboehm/mailserver-mda:latest
    build: ./mda
    container_name: mailserver_mda
    restart: on-failure:5
    env_file: .env
    volumes:
      - data_mail:/var/vmail
      - data_tls:/media/tls:ro
      # For using external certificates uncomment the following lines
      # and change the path on the left side of the colon.
      # - /home/user/certs/mail.example.com.crt:/media/tls/mailserver.crt:ro
      # - /home/user/certs/mail.example.com.key:/media/tls/mailserver.key:ro

  # The admin (mailserver-admin) and webmail (roundcube) interfaces
  # live here. Can be removed if not needed.
  web:
    image: jeboehm/mailserver-web:latest
    build: ./web
    container_name: mailserver_web
    restart: on-failure:5
    env_file: .env
    volumes:
      - data_dkim:/media/dkim
    # For use with jwilder/nginx-proxy.
    # environment:
    #   - VIRTUAL_HOST=mail.example.com

  # Incoming spam is (hopefully) filtered by rspamd which runs
  # in this service.
  filter:
    image: jeboehm/mailserver-filter:latest
    build: ./filter
    container_name: mailserver_filter
    restart: on-failure:5
    env_file: .env
    volumes:
      - data_filter:/var/lib/rspamd
      - data_dkim:/media/dkim
    links:
      - virus:virus.local

  # Incoming viruses or malware is detected and rejected by
  # this service. Can be removed if FILTER_VIRUS is set to false.
  virus:
    image: jeboehm/mailserver-virus:latest
    build: ./virus
    container_name: mailserver_virus
    restart: on-failure:5
    env_file: .env
    volumes:
      - data_virusdb:/var/lib/clamav

  # If you want unhealthy containers to be restarted automatically
  # just uncomment the following lines.
  # autoheal:
  #   image: willfarrell/autoheal:latest
  #   restart: always
  #   networks: []
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=de.ressourcenkonflikt.docker-mailserver.autoheal

  # Optional service: extend ClamAV (used in the virus service)
  # by downloading additional databases provided by different
  # companys. Run it regulary.
  # virus_unof_sig_updater:
  #   build: ./virus/contrib/unofficial-sigs
  #   env_file: .env
  #   volumes:
  #     - data_virusdb:/var/lib/clamav

volumes:
  data_db:
  data_dkim:
  data_mail:
  data_tls:
  data_filter:
  data_virusdb:
